### ISSUE TITLE
Elementos a aportar

### ISSUE THREAD

**Issue by jmaurici** [LKO124/JavaEE_Practices#1]
Hola Jorge.

Debes subir:

1. backup BBDD 
2. la memoria de las especificaciones con los cambios introducidos en las reuniones 
3. un LEEME, explicando cómo arrancar tu proyecto (Eclipse, NetBeans..)

Un saludo
JMauricio

**Comment by LKO124** [comment]
Buenas tardes, Mauricio.
La bbdd ya esta añadida junto con el leeme, y en cuanto a la memoria se encuentra disponible desde prácticamente la creación del repositorio en el siguiente link: [https://github.com/LKO124/JavaEE_Practices/blob/master/ProyectoJavaEE/Informe%20proyecto.pdf](url)
